### ISSUE TITLE
一种页面加载显示效果优化方案

### ISSUE THREAD

**Issue by RenderCoder** [Product-Engineer/FAQ#14]
载入页面时，页面会先显示 HTML5 开发的默认数据或空数据，获取到设备的数据后，才显示正确的数据。中间会有 1-N 秒的过程，影响用户体验。

可以仿照阿里智能安卓默认的加载遮罩，在页面加载到第一次设备数据前，显示一个全屏遮罩，获取到之后，再显示设备页面。如图：
![](http://okw4n9e5h.bkt.clouddn.com/034955.jpg)

具体代码：

### HTML

具体 iconfont 字体图标，在 `iconfont.cn` 搜索阿里智能就可找到，加入到项目的字体图标库里面即可。

```html
<div class="loading-view">
    <div class="loading-icon">
        <div class="iconfont">&#xe633;</div>
    </div>
    <div class="loading-text">加载中...</div>
</div>
```

### CSS

```css
.loading-view {
    box-sizing: border-box;
    position: fixed;
    top: 50%;
    left: 50%;
    background-color: #000000;
    width: 120px;
    height: 120px;
    margin-left: -60px;
    margin-top: -100px;
    padding-top: 30px;
    color: #ffffff;
    z-index: 999;
}
.loading-view:before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    background-color: rgba(255,255,255,1);
}
.loading-view .loading-icon {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: #CCCCCC;
    text-align: center;
    border-radius: 50%;
    overflow: hidden;
}
.loading-view .loading-icon .iconfont {
    font-size: 80px;
    line-height: 120px;
}
.loading-view .loading-text {
    position: absolute;
    top: 140px;
    left: 0;
    width: 100%;
    text-align: center;
    color: #CCCCCC;
    font-size: 14px;

}
```
